// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMdiMX_oUCSYRoaMkonav8asxEap4eljY',
    appId: '1:17204905981:android:3efd606248fb55d6103b94',
    messagingSenderId: '17204905981',
    projectId: 'zimmet-takip-9ece5',
    storageBucket: 'zimmet-takip-9ece5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR2K8UE2e48IVcMjeWZmHSyiVwI-i4Th4',
    appId: '1:17204905981:ios:c18f4f9b5e5aff42103b94',
    messagingSenderId: '17204905981',
    projectId: 'zimmet-takip-9ece5',
    storageBucket: 'zimmet-takip-9ece5.firebasestorage.app',
    iosBundleId: 'com.example.zimmetTakip',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMN7A8orualcnlYjzH4_n1g0mKLr91JR4',
    appId: '1:17204905981:web:d575d6dc6cc0eca3103b94',
    messagingSenderId: '17204905981',
    projectId: 'zimmet-takip-9ece5',
    authDomain: 'zimmet-takip-9ece5.firebaseapp.com',
    storageBucket: 'zimmet-takip-9ece5.firebasestorage.app',
  );
}
